config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :workers
  resources :shifts, only: [:create, :index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :worker
  validates :worker_id, presence: true
  validates :start_date, presence: true, uniqueness: { scope: :worker_id }
end

app/models/worker.rb
class Worker < ApplicationRecord
  has_many :shifts, dependent: :destroy

  validates :first_name, presence: true, length: { maximum: 50 },
                   uniqueness: { case_sensitive: false }
  validates :status, presence: true, inclusion: { in: %w(medic interne interim),
                                     message: "%{value} is not a valid status" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  def index
    @shift = Shift.new
    @shifts = Shift.all
    @workers = Worker.all
  end

  def create
    worker = Worker.find(shift_params[:worker_id])
    @shift = worker.shifts.build(shift_params)
    if @shift.save
      flash[:success] = "Shift successfully added for #{worker.first_name}."
      redirect_to shifts_url
    else
      @shifts = Shift.all
      @workers = Worker.all
      render 'shifts/index'
    end
  end

  def destroy
    Shift.find(params[:id]).destroy
    flash[:success] = "Shift deleted"
    redirect_to shifts_url
  end

  private

    def shift_params
      params.require(:shift).permit(:worker_id, :start_date)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  def index
    @worker = Worker.new
    @workers = Worker.all
  end

  def show
    @worker = Worker.find(params[:id])
  end

  def create
    @worker = Worker.new(worker_params)
    if @worker.save
      flash[:success] = "Worker successfully created !"
      redirect_to edit_worker_path(@worker)
    else
      @workers = Worker.all
      render 'index'
    end
  end

  def edit
    @worker = Worker.find(params[:id])
  end

  def update
    @worker = Worker.find(params[:id])
    if @worker.update_attributes(worker_params)
      flash[:success] = "Worker updated !"
      redirect_to edit_worker_path(@worker)
    else
      render 'edit'
    end
  end

  def destroy
    Worker.find(params[:id]).destroy
    flash[:success] = "Worker deleted"
    redirect_to workers_path
  end

  private

    def worker_params
      params.require(:worker).permit(:first_name, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <div class="logo">
      <%= link_to root_path, id: "logo-text" do %>
        <%= image_tag 'hospital.png', id: "logo" %> Night Shift Manager
      <% end %>
    </div>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Shifts", shifts_path %></li>
        <li><%= link_to "Workers", workers_path %></li>
      </ul>
    </nav>
  </div><!-- /container-fluid -->
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShiftManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div><!-- /container -->
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shifts/_form.html.erb
<%= form_for(@shift) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="form-group">
    <h4>- Start Date -</h4>
    <%= f.date_select :start_date, class: 'form-control' %>
  </div>

  <div class="form-group">
    <h4>- Worker -</h4>

    <%= f.select(:worker_id, Worker.all.collect { |w| [w.first_name, w.id] }) %>

  </div>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>
<p class="note">Please note that a worker can't have more than 1 shift on a given day.</p>

app/views/shifts/_shift.html.erb
<div class="shift">
  <span>Start date : <%= shift.start_date %></span>
  <span> Worker : <%= shift.worker.first_name %></span>
  <span><%= link_to "X", shift, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-danger btn-xs" %></span>
</div>

app/views/shifts/index.html.erb
<% provide(:button_text, 'Create') %>

<div class="row index-head">
  <h2>Add a new shift <i class="fa fa-calendar"></i></h2>

  <% unless @workers.empty? %>
    <%= render 'form' %>
  <% else %>
    <div class="main">
      <h3>Please add some workers first</h3>
    </div>
  <% end %>
</div><!-- /row -->

<h2>Shifts list</h2>
<div class="row list">
  <%= render @shifts %>
</div><!-- /row -->

app/views/static_pages/home.html.erb
<div class="row" id="background-title">
  <h1 class="text-center">Welcome to Night Shift Manager</h1>
  <h5 class="text-center">Manage your medic staff and its shifts</h5>
</div><!-- /row -->

<div class="row">
  <div class="main">
    <h4>Add new workers and edit existing ones :</h4>
    <%= link_to workers_path, class: "btn btn-lg btn-success" do %>
        Workers <i class="fa fa-user-md fa-lg"></i>
      <% end %>
    <h4>Create and assign shifts :</h4>
    <%= link_to shifts_path, class: "btn btn-lg btn-info" do %>
        Shifts <i class="fa fa-calendar"></i>
      <% end %>
  </div>
</div><!-- /row -->

app/views/workers/_form.html.erb
<%= form_for(@worker) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="form-group">
    <h4>- First Name -</h4>
    <%= f.text_field :first_name, class: 'form-control', placeholder: "Doc" %>
  </div>

  <div class="form-group">
    <h4>- Status -</h4>

    <%= f.radio_button :status, "medic", checked: "checked" %>
    <%= f.label :status_medic, "Medic" %>

    <%= f.radio_button :status, "interne" %>
    <%= f.label :status_interne, "Interne" %>

    <%= f.radio_button :status, "interim" %>
    <%= f.label :status_interim, "Interim" %>
  </div>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/workers/_worker.html.erb
<%= tag.div class: ["worker", worker.status] do %>
  <b><%= worker.first_name.capitalize %></b>

  <span>
    <%= worker.status.capitalize %>

    <!-- Add special icon -->
    <% case worker.status %>
    <% when "medic" %>
      <i class="fa fa-stethoscope fa-2x"></i>
    <% when "interne" %>
      <i class="fa fa-graduation-cap fa-2x"></i>
    <% else %>
      <i class="fa fa-ambulance fa-2x"></i>
    <% end %>
  </span>

  <span>
    <%= worker.shifts.count %> shift(s) planned
  </span>

  <%= link_to "Edit", edit_worker_path(worker), class: "btn btn btn-warning" %>
<% end %>

app/views/workers/edit.html.erb
<% provide(:button_text, 'Save changes') %>

<div class="row edit-head">
  <h2>Edit worker information</h2>
  <%= render 'form' %>
</div><!-- /row -->

<div class="row">
  <div class="delete">
    <%= link_to "Delete worker", @worker, method: :delete,
                data: { confirm: "Are you sure?" },
                class: ["btn", "btn-danger"] %>
  </div>
</div><!-- /row -->

app/views/workers/index.html.erb
<% provide(:button_text, 'Create') %>

<div class="row index-head">
  <h2>Add a new worker <i class="fa fa-user-md fa-lg" aria-hidden="true"></i>
</h2>
  <%= render 'form' %>
</div><!-- /row -->

<h2>Workers list</h2>
<div class="row list">
  <%= render @workers %>
</div><!-- /row -->

app/views/workers/show.html.erb
<%= @worker.first_name %> - <%= @worker.status %>